# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  #   vb.memory = "1024"
  end

  config.vm.provision "ansible" do |a|
    a.playbook = "provisioning/playbook.yml"
    a.verbose = 'vvv'
  end
end
