<?php if(!$this->canWork()):?>
<p><?php echo $this->__('Cashway is actually not available.')?><p>
<script type="text/javascript">
 	//<![CDATA[
 		
 		$('p_method_cashway').disable();
 		
 	//]]>
 </script>
<?php else:?>
<!--  <h4>Les points de paiement présents autour de votre point de livraison&nbsp;:</h4>
        <input id="address" type="textbox" value="<?php echo $this->getAdressOneLine() ?>" onsubmit="codeLocation();" />
        <input type="button" value="Trouver les points de paiement CashWay autour de cette adresse" onclick="codeLocation();" />
        <div id="map-canvas" style="width: 100%; height: 400px;"></div>
        <script type="text/javascript" src="https://maps.cashway.fr/js/cashway_map.js"></script>-->
<?php endif;?>
