<!-- 
/**
 *  CASHWAY
 *
 *  Copyright 2015 CashWay
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @category   Sirateck
 * @package    Sirateck_Cashway
 * @copyright  Copyright 2015 CashWay
 * @license    http://www.apache.org/licenses/LICENSE-2.0  Apache License, Version 2.0
 */
 -->
<?php if(!$this->canWork()):?>
<p><?php echo $this->__('Cashway is actually not available.')?><p>
<script type="text/javascript">
 	//<![CDATA[
 		
 		$('p_method_cashway').disable();
 		
 	//]]>
 </script>
<?php else:?>
<!--  <h4>Les points de paiement présents autour de votre point de livraison&nbsp;:</h4>
        <input id="address" type="textbox" value="<?php echo $this->getAddressOneLine() ?>" onsubmit="codeLocation();" />
        <input type="button" value="Trouver les points de paiement CashWay autour de cette adresse" onclick="codeLocation();" />
        <div id="map-canvas" style="width: 100%; height: 400px;"></div>
        <script type="text/javascript" src="https://maps.cashway.fr/js/cashway_map.js"></script>-->
<?php endif;?>
