source 'https://rubygems.org'

gem 'addressable', '2.3.8'
gem 'mime-types', '2.6.2'
gem 'mini_portile', '0.6.2'
gem 'nokogiri', '1.6.6.2'
gem 'childprocess', '0.5.6'
gem 'selenium-webdriver', '2.47.1'
